language: python
python:
  - "2.7"
  - "3.4"

sudo: required
dist: trusty    # We want a recent SciPy.

addons:
  apt:
    packages:
      - python-numpy
      - python-scipy
      - python3-numpy
      - python3-scipy
      - libatlas-dev
      - liblapack-dev
      - gfortran

virtualenv:
  system_site_packages: true

install:
  - deactivate
  - virtualenv --system-site-packages testenv
  - source testenv/bin/activate
  - pip install -U Cython nose scikit-learn
  - pip install .

script:
  - cd /tmp
  - nosetests --exe seqlearn
